name: GitHub Actions CI

on:
  push:
    branches: 
      - main
      - build-with-ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: df -h
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build docker/ -t benchmarks
      - run: docker tag benchmarks ${{ secrets.DOCKER_USERNAME }}/benchmarks
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/benchmarks

  run:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: docker run -t --rm -v  $(pwd):/src ${{ secrets.DOCKER_USERNAME }}/benchmarks base64 bench
